# 🚀 Jira MCP Server - Smithery Minimal (Core Service Only)
# Optimized for Smithery deployment with minimal dependencies

services:
  # Main Jira MCP Server - HTTP Mode Only
  jira-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-mcp-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MODE=http
      - PORT=3000
      - JIRA_URL=${JIRA_URL}
      - JIRA_EMAIL=${JIRA_EMAIL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
      - ENABLE_CACHING=false
      - LOG_LEVEL=info
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
        reservations:
          memory: 128M
          cpus: '0.1'

networks:
  jira-mcp-network:
    driver: bridge
    name: jira-mcp-network