# Simplified Prometheus configuration for Smithery deployment
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Jira MCP Server health endpoint
  - job_name: "jira-mcp-server"
    static_configs:
      - targets: ["jira-mcp-server:3000"]
    metrics_path: "/health"
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis monitoring
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s
