# Prometheus configuration for Jira MCP Server monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Jira MCP Server metrics (when metrics endpoint is implemented)
  - job_name: "jira-mcp-server"
    static_configs:
      - targets: ["jira-mcp-server:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter for system metrics
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s

  # Docker container metrics
  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]
    scrape_interval: 30s

  # Redis metrics (if using Redis for caching)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention_time: "15d"
    retention_size: "10GB"
